# replacement strings
WINDOWS_LINE_ENDING = b'\r\n'
UNIX_LINE_ENDING = b'\n'

# relative or absolute file path, e.g.:
file_path = r"c:\Users\Username\Desktop\file.txt"

with open(file_path, 'rb') as open_file:
    content = open_file.read()

content = content.replace(WINDOWS_LINE_ENDING, UNIX_LINE_ENDING)

with open(file_path, 'wb') as open_file:
    open_file.write(content)


    import csv

# ----------------------------------------------------------------------------------
#
#  Generated by the ReCsvEditor (https://sourceforge.net/projects/recsveditor)
#  on the 1 mai 2019 22:48:47.
#
#  I am not a Python Csv programer, So please make suggestions !!!
#
# ----------------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# In this Class each field represents an index of a field in the CSV file.
# Using this class  you to use meaningful names (instead on index numbers)
# and code completion (if your editor supports Code completion)
# ---------------------------------------------------------------------------
class indexs:
    nconst = 0
    primaryname = 1
    birthyear = 2
    deathyear = 3
    primaryprofession = 4
    knownfortitles = 5
                                               
    Column_Count = 6                                                                      

def read_data(path):
    with open(path, 'rb') as csvfile:
        csvReader = csv.reader(csvfile, delimiter='\t')
        next(csvReader)
        for row in csvReader:
            yield row

# -------------------------------------------------------

if __name__ == "__main__":
    idx = indexs()
    
    for rowIndex, row in enumerate(read_data('C:\\Users\\caesa\\Downloads\\data.tsv')):
        print row[idx.nconst], row[idx.primaryname], row[idx.birthyear]
